# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '场地信息', 'verbose_name_plural': '场地信息'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '工坊信息', 'verbose_name_plural': '工坊信息'},
        ),
    ]
