# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0006_auto_20171007_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='instructor',
        ),
    ]
