# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UID')),
                ('scheme', models.CharField(max_length=10, verbose_name='Scheme')),
                ('request_uri', models.CharField(max_length=256, verbose_name='Path')),
                ('request_method', models.CharField(max_length=10, verbose_name='Method')),
                ('request_referer', models.CharField(max_length=256, verbose_name='Referer')),
                ('request_user_agent', models.CharField(max_length=256, verbose_name='User-Agent')),
                ('request_user_id', models.CharField(max_length=11, verbose_name='User ID')),
                ('request_user_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('response_status_code', models.CharField(max_length=3, verbose_name='Status Code')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'BehaviorFlow',
                'verbose_name_plural': 'BehaviorFlow',
            },
        ),
    ]
