# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorflow',
            name='uid',
        ),
    ]
