# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_remove_behaviorflow_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorflow',
            name='response_render_time',
            field=models.FloatField(default=0, verbose_name='Response Render Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='behaviorflow',
            name='request_uri',
            field=models.CharField(max_length=256, verbose_name='URI'),
        ),
    ]
