# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teacher_info', serialize=False, to='authentication.UserInfo')),
                ('title', models.IntegerField(choices=[(0, '工程师'), (1, '高级工程师'), (2, '讲师'), (3, '副教授'), (4, '教授')], default=0, verbose_name='职务')),
            ],
            options={
                'verbose_name': '指导教师信息',
                'verbose_name_plural': '指导教师信息',
            },
            bases=('authentication.userinfo',),
        ),
    ]
