# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_teacherinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialinfo',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '社会人员信息', 'verbose_name_plural': '社会人员信息'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '指导教师信息', 'verbose_name_plural': '指导教师信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '基本信息', 'verbose_name_plural': '基本信息'},
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='social_info', serialize=False, to='authentication.UserInfo', verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='student_info', serialize=False, to='authentication.UserInfo', verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
