# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170908_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinfo',
            name='user_info',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='identity',
            field=models.IntegerField(choices=[(0, '超级管理员'), (1, '平台管理员'), (2, '教师'), (3, '学生')], default=-1, verbose_name='身份'),
        ),
        migrations.DeleteModel(
            name='SocialInfo',
        ),
    ]
