# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SiteReservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_from',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_to',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='预约时间'),
            preserve_default=False,
        ),
    ]
