# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteReservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '活动场地预约', 'verbose_name_plural': '活动场地预约'},
        ),
    ]
