# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteReservation', '0002_auto_20170915_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, '预约已提交'), (1, '预约已取消'), (2, '预约已批准'), (3, '预约修改中'), (4, '预约已终止')], default=0, verbose_name='状态'),
        ),
    ]
