# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteReservation', '0003_auto_20170920_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': 'Site Reservation', 'verbose_name_plural': 'Site Reservation'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activity_time_from',
            field=models.DateTimeField(verbose_name='Activity Time From'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activity_time_to',
            field=models.DateTimeField(verbose_name='Activity Time To'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reservation Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, '预约已提交'), (1, '预约已取消'), (2, '预约已批准'), (3, '预约修改中'), (4, '预约已终止')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.Workshop', verbose_name='Workshop'),
        ),
    ]
