# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteReservation', '0004_auto_20171004_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Reservation Submitted'), (1, 'Reservation Cancelled'), (2, 'Reservation Approved'), (3, 'Reservation Editting'), (4, 'Reservation Terminated')], default=0, verbose_name='Status'),
        ),
    ]
