# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_teacherinfo'),
        ('const', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, '申请已提交'), (1, '申请已取消'), (2, '活动进行中'), (3, '申请修改中'), (4, '活动已终止'), (5, '结项待审核'), (6, '结项修改中'), (7, '活动已完成'), (8, '活动已报销')], default=0, verbose_name='状态')),
                ('title', models.CharField(max_length=100, verbose_name='活动内容')),
                ('activity_time_from', models.DateTimeField(verbose_name='活动开始时间')),
                ('activity_time_to', models.DateTimeField(verbose_name='活动结束时间')),
                ('site', models.CharField(max_length=100, verbose_name='活动场地')),
                ('form', models.CharField(max_length=30, verbose_name='活动形式')),
                ('charger', models.CharField(max_length=20, verbose_name='活动负责人')),
                ('contact_info', models.CharField(max_length=30, verbose_name='联系方式')),
                ('activity_range', models.IntegerField(choices=[(0, '工坊内部'), (1, '全校')], default=0, verbose_name='活动范围')),
                ('amount', models.IntegerField(verbose_name='参与人数')),
                ('has_social', models.BooleanField(verbose_name='是否有校外人员参与')),
                ('budget', models.TextField(verbose_name='活动预算及说明')),
                ('comment', models.TextField(verbose_name='备注')),
                ('instructor_comment', models.TextField(verbose_name='指导教师意见')),
                ('institute_comment', models.TextField(verbose_name='学院意见')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.TeacherInfo', verbose_name='指导教师')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.Workshop', verbose_name='工坊')),
            ],
            options={
                'verbose_name': '活动场地预约',
                'verbose_name_plural': '活动场地预约',
            },
        ),
    ]
