# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 02:00
from __future__ import unicode_literals

import ProjectApproval.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('socials_info', models.TextField(verbose_name='校外人员名单')),
                ('attend_info', models.TextField(verbose_name='校外人员参与活动情况说明')),
                ('ideology_info', models.TextField(verbose_name='校外人员思想意识形态情况说明')),
            ],
            options={
                'verbose_name': '邀请校外人员申请表',
                'verbose_name_plural': '邀请校外人员申请表',
                'default_permissions': ('add', 'delete', 'update', 'view'),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': '活动项目', 'verbose_name_plural': '活动项目'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='institute_comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(upload_to=ProjectApproval.utils.get_user_project_attachments_path, verbose_name='上传附件'),
        ),
        migrations.AddField(
            model_name='socialinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApproval.Project', verbose_name='活动项目'),
        ),
    ]
