# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 07:07
from __future__ import unicode_literals

import ProjectApproval.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0002_auto_20170914_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, upload_to=ProjectApproval.utils.get_user_project_attachments_path, verbose_name='上传附件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instructor_comment',
            field=models.TextField(blank=True, verbose_name='指导教师意见'),
        ),
    ]
