# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0003_auto_20170915_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='申请时间'),
            preserve_default=False,
        ),
    ]
