# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0005_auto_20170923_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='', verbose_name='活动内容'),
        ),
    ]
