# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 07:51
from __future__ import unicode_literals

import ProjectApproval.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0006_project_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='socialinvitation',
            options={'default_permissions': ('add', 'delete', 'update', 'view'), 'verbose_name': 'Social Invitation', 'verbose_name_plural': 'Social Invitation'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='instructor_comment',
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_range',
            field=models.IntegerField(choices=[(0, '工坊内部'), (1, '全校')], default=0, verbose_name='Project Participant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_time_from',
            field=models.DateTimeField(verbose_name='Activity Time From'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_time_to',
            field=models.DateTimeField(verbose_name='Activity Time To'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.IntegerField(verbose_name='Participant Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Apply Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, upload_to=ProjectApproval.utils.get_user_project_attachments_path, verbose_name='Project Attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.TextField(verbose_name='Budget Detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='charger',
            field=models.CharField(max_length=20, verbose_name='Person in Charge'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_info',
            field=models.CharField(max_length=30, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(default='', verbose_name='Project Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='form',
            field=models.CharField(max_length=30, verbose_name='Project Form'),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_social',
            field=models.BooleanField(verbose_name='Has Social'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(-1, '校外人员表单待填写'), (0, '申请已提交'), (1, '申请已取消'), (2, '活动进行中'), (3, '申请修改中'), (4, '活动已终止'), (5, '结项待审核'), (6, '结项修改中'), (7, '活动已完成'), (8, '活动已报销')], default=0, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.Workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='socialinvitation',
            name='attend_info',
            field=models.TextField(verbose_name='Social Attend Info'),
        ),
        migrations.AlterField(
            model_name='socialinvitation',
            name='ideology_info',
            field=models.TextField(verbose_name='Social Ideology Info'),
        ),
        migrations.AlterField(
            model_name='socialinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApproval.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='socialinvitation',
            name='socials_info',
            field=models.TextField(verbose_name='Social List'),
        ),
    ]
