# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0008_auto_20171007_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='form',
            field=models.IntegerField(choices=[(0, 'Free To Join'), (1, 'Limited Invivation'), (2, 'Advance Reservation'), (3, 'Others')], verbose_name='Project Form'),
        ),
    ]
