# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApproval', '0009_auto_20171009_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(max_length=30, verbose_name='Budget Item')),
                ('amount', models.FloatField(verbose_name='Budget Amount')),
                ('detail', models.CharField(max_length=50, verbose_name='Budget Detail')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budget',
                'default_permissions': ('add', 'delete', 'update', 'view'),
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApproval.Project', verbose_name='Project'),
        ),
    ]
