#!/usr/bin/env python3
# coding: UTF-8
# Author: David
# Email: youchen.du@gmail.com
# Created: 2017-09-07 19:34
# Last modified: 2017-10-04 16:17
# Filename: __init__.py
# Description:
from django.utils.translation import ugettext_lazy as _


PROJECT_SUBMITTED = 0
PROJECT_CANCELLED = 1
PROJECT_APPROVED = 2
PROJECT_EDITTING = 3
PROJECT_TERMINATED = 4
PROJECT_END_SUBMITTED = 5
PROJECT_END_EDITTING = 6
PROJECT_FINISHED = 7
PROJECT_COMPLETED = 8
PROJECT_SOCIALFORM_REQUIRED = 9
PROJECT_STATUS = (
    (PROJECT_SUBMITTED, _('Project Submitted')),
    (PROJECT_CANCELLED, _('Project Cancelled')),
    (PROJECT_APPROVED, _('Project Approved')),
    (PROJECT_EDITTING, _('Project Editting')),
    (PROJECT_TERMINATED, _('Project Terminated')),
    (PROJECT_END_SUBMITTED, _('Project End Submitted')),
    (PROJECT_END_EDITTING, _('Project End Editting')),
    (PROJECT_FINISHED, _('Project Finished')),
    (PROJECT_COMPLETED, _('Project Completed')),
    (PROJECT_SOCIALFORM_REQUIRED, _('Additional Info Required')),
)


ACTIVITY_RANGE_WORKSHOP = 0
ACTIVITY_RANGE_SCHOOL = 1
ACTIVITY_RANGES = (
    (ACTIVITY_RANGE_WORKSHOP, _('Within Workshop')),
    (ACTIVITY_RANGE_SCHOOL, _('Whole School')),
)


PROJECT_STATUS_CAN_EDIT = (
    PROJECT_SUBMITTED, PROJECT_EDITTING,
    PROJECT_SOCIALFORM_REQUIRED)

PROJECT_STATUS_CAN_CHECK = (
    PROJECT_SUBMITTED, PROJECT_APPROVED,
    PROJECT_EDITTING, PROJECT_TERMINATED)

PROJECT_STATUS_CAN_CANCEL = (
    PROJECT_SUBMITTED, PROJECT_EDITTING,
    PROJECT_SOCIALFORM_REQUIRED)

PROJECT_STATUS_CAN_EXPORT = (PROJECT_APPROVED,)
