from ProjectApproval import PROJECT_SUBMITTED, PROJECT_CANCELLED
from ProjectApproval import PROJECT_APPROVED, PROJECT_EDITTING
from ProjectApproval import PROJECT_TERMINATED, PROJECT_END_CONFIRMED
from ProjectApproval import PROJECT_END_EDITTING, PROJECT_FINISHED
from ProjectApproval import PROJECT_COMPLETED
from ProjectApproval import PROJECT_STATUS_CAN_EDIT
from ProjectApproval import PROJECT_STATUS_CAN_CHECK
from ProjectApproval import PROJECT_STATUS_CAN_CANCEL
from ProjectApproval import PROJECT_STATUS_CAN_EXPORT
from ProjectApproval import PROJECT_HASSOCIAL


def expose_consts(request):
    consts = {
        'PROJECT_SUBMITTED': PROJECT_SUBMITTED,
        'PROJECT_CANCELLED': PROJECT_CANCELLED,
        'PROJECT_APPROVED': PROJECT_APPROVED,
        'PROJECT_EDITTING': PROJECT_EDITTING,
        'PROJECT_TERMINATED': PROJECT_TERMINATED,
        'PROJECT_END_CONFIRMED': PROJECT_END_CONFIRMED,
        'PROJECT_END_EDITTING': PROJECT_END_EDITTING,
        'PROJECT_FINISHED': PROJECT_FINISHED,
        'PROJECT_COMPLETED': PROJECT_COMPLETED,
        'PROJECT_STATUS_CAN_EDIT': PROJECT_STATUS_CAN_EDIT,
        'PROJECT_STATUS_CAN_CANCEL': PROJECT_STATUS_CAN_CANCEL,
        'PROJECT_STATUS_CAN_CHECK': PROJECT_STATUS_CAN_CHECK,
        'PROJECT_HASSOCIAL': PROJECT_HASSOCIAL,
        'PROJECT_STATUS_CAN_EXPORT': PROJECT_STATUS_CAN_EXPORT,
    }
    return consts
